services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: addicted
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  supersubtitles:
    image: ghcr.io/belphemur/supersubtitles:latest
    container_name: supersubtitles
    environment:
      APP_SERVER_ADDRESS: "0.0.0.0"
      APP_SERVER_PORT: "8080"
    ports:
      - "3001:8080"
    restart: unless-stopped

volumes:
  postgres_data:
